PackageIdentifier: novafabric.YazSes
PackageVersion: 1.0.0-dev.1
MinimumOSVersion: "10.0.19041.0"
InstallerType: zip
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/novafabric/yazses/releases/download/v1.0.0-dev.1/yazses-v1.0.0-dev.1-x86_64-pc-windows-msvc.zip
    InstallerSha256: PLACEHOLDER_WIN64_SHA256
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: yazses-v1.0.0-dev.1-x86_64-pc-windows-msvc\yazses.exe
        PortableCommandAlias: yazses
      - RelativeFilePath: yazses-v1.0.0-dev.1-x86_64-pc-windows-msvc\yazses-daemon.exe
        PortableCommandAlias: yazses-daemon
InstallModes:
  - interactive
  - silent
ManifestType: installer
ManifestVersion: 1.6.0
