from typing import Protocol, runtime_checkable


@runtime_checkable
class BaseInjector(Protocol):
    def inject(self, text: str) -> None: ...
    def inject_backspaces(self, count: int) -> None: ...
    def inject_key_sequence(self, keys: list[str]) -> None: ...
